### PR TITLE
Update to Phoenix 1.6 for #17

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] Update to Phoenix 1.6 for #17 🚀 
  + [x] Deletes `package.json` and unnecessary node.js dependencies! 🎉 
+ [x] Update underlying dependency `elixir_auth_github` to `1.5.0` 📦

### CODE REVIEW

**Comment by nelsonic** [comment]
Works flawlessly on `localhost` with latest Elixir & Phoenix: 
image

# 🚀

**Comment by nelsonic** [comment]
@iteles please review/merge when you can. Thanks. ☀️

**Comment by nelsonic** [comment]
@iteles merge when you can. Thanks.

**Review by iteles — APPROVED** [review]
Looks to be working on my localhost too. Thanks @nelsonic !

**Pull request merged**
