### PR TITLE
Update to latest version of elixir-auth-github 

### PR DESCRIPTION
**Pull request by nelsonic**
As per: https://github.com/dwyl/elixir-auth-github/issues/46 updating to latest version. ✅

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab once you've reviewed+merged this PR,
please confirm that it deployed successfully: https://dashboard.heroku.com/apps/elixir-auth-github-demo/deploy/github
Thanks. 👍

**Review by SimonLab — APPROVED** [review]
:+1:

**Comment by SimonLab** [comment]
The build is failing on Heroku, conflict of elixir versions:
image

**Comment by nelsonic** [comment]
@SimonLab #7 |> #8 😉

**Pull request merged**
